PruebaCapital/urls.py
# Django
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include(("usuarios.urls", "usuarios"), namespace="usuarios")),
    path("", include(("vehiculos.urls", "vehiculos"), namespace="vehiculos")),
]

usuarios/urls.py
# Django
from django.urls import path

# View
from usuarios import views


urlpatterns = [
    path(
        route="login",
        view=views.LoginView.as_view(),
        name='login'
    ),
    path(
        route="logout",
        view=views.LogoutView.as_view(),
        name='logout'
    ),
    path(
        route="signup",
        view=views.SignupView.as_view(),
        name='signup'
    ),
]

vehiculos/urls.py
# Django
from django.urls import path

# View
from vehiculos import views


urlpatterns = [
    path(
        route="registro_vehiculo",
        view=views.RegisterVehicleView.as_view(),
        name='registro_vehiculo'
    ),
    path(
        route="crear_evento",
        view=views.CreateEventView.as_view(),
        name='crear_evento'
    ),
    path(
        route="crear_invitacion",
        view=views.CreateInvitationView.as_view(),
        name='crear_invitacion'
    ),
    path(
        route="status_invitacion",
        view=views.InvitationStatusView.as_view(),
        name='status_invitacion'
    ),
    path(
        route="get_info",
        view=views.GetInfoView.as_view(),
        name='get_info'
    ),
]

vehiculos/models.py
# Django
from django.core.exceptions import ValidationError
from django.db import models


class Vehiculo(models.Model):

    marca = models.CharField(max_length=255)
    modelo = models.CharField(max_length=255)
    num_serie = models.CharField(max_length=255)
    num_placas = models.CharField(max_length=255, unique=True)
    conductor = models.ForeignKey(
        "usuarios.Perfil",
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )

    def __str__(self):
        return f"{self.marca} {self.modelo} - {self.num_placas}"


class Invitado(models.Model):

    num_placas = models.CharField(max_length=255)
    vehiculo = models.ForeignKey(
        "Vehiculo",
        on_delete=models.SET_NULL,
        related_name='invitaciones',
        null=True,
        blank=True
    )
    evento = models.ForeignKey(
        "Evento",
        on_delete=models.CASCADE,
        related_name='invitados'
    )

    hora_entrada = models.DateTimeField(null=True, blank=True)
    hora_salida = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f"{self.num_placas} - {self.evento}"

    def clean(self):
        if self.evento.invitados.count() >= self.evento.max_invitados:
            raise ValidationError(
                "La lista de invitados ha alcanzado su "
                "número máximo de invitados."
            )
        
        misma_invitacion = self.evento.invitados.filter(
            num_placas=self.num_placas
        ).exclude(pk=self.pk)

        if misma_invitacion.exists():
            raise ValidationError(
                "Ya existe una invitación con estas placas en el mismo evento."
            )


class Evento(models.Model):
    nombre = models.CharField(max_length=255)
    dueño = models.ForeignKey("usuarios.Perfil", on_delete=models.CASCADE)
    max_invitados = models.PositiveIntegerField(default=100)

    def __str__(self):
        return self.nombre

vehiculos/views.py
# Django
from django.db.models import Case, When, CharField, Value
from django.http import HttpResponseRedirect
from django.http.response import JsonResponse
from django.urls import reverse_lazy

# Django REST Framework
from rest_framework.generics import GenericAPIView
from rest_framework.permissions import IsAuthenticated
from rest_framework.renderers import JSONRenderer, TemplateHTMLRenderer
from rest_framework.response import Response

# Models
from vehiculos.models import Vehiculo, Invitado, Evento

# Permissions
from usuarios.permissions import IsStaff
from vehiculos.permissions import IsEventOwner

# Serializers
from vehiculos.serializers import (
    VehiculoSerializer,
    EventoSerializer,
    InvitadoSerializer
)

# Utils
import datetime


# Vista de la pantalla para Registrar Vehículos
class RegisterVehicleView(GenericAPIView):
    template_name = 'vehiculos/registro.html'
    renderer_classes = [JSONRenderer, TemplateHTMLRenderer]

    permission_classes = [IsAuthenticated]

    def get(self, request):
        """Método Get: pasa todo el contexto necesario para la vista."""
        return Response()

    def post(self, request):
        """Método Post: maneja la creación del vehiculo."""

        r = request.POST
        marca = r.get("marca")
        modelo = r.get("modelo")
        num_serie = r.get("num_serie")
        num_placas = r.get("num_placas")

        vehiculo = Vehiculo.objects.create(
            marca=marca,
            modelo=modelo,
            num_serie=num_serie,
            num_placas=num_placas,
            conductor=self.request.user.perfil,
        )

        Invitado.objects.filter(
            num_placas=vehiculo.num_placas
        ).update(vehiculo=vehiculo)

        if "text/html" in self.request.accepted_media_type:
            return HttpResponseRedirect(
                reverse_lazy('vehiculos:registro_vehiculo')
            )
        else:
            return JsonResponse(VehiculoSerializer(vehiculo).data, safe=False)


# Vista de la pantalla para Crear Evento
class CreateEventView(GenericAPIView):
    template_name = 'vehiculos/crear_evento.html'
    renderer_classes = [JSONRenderer, TemplateHTMLRenderer]

    permission_classes = [IsAuthenticated]

    def get(self, request):
        """Método Get: pasa todo el contexto necesario para la vista."""
        return Response()

    def post(self, request):
        """Método Post: maneja la creación del evento."""

        r = request.POST
        nombre = r.get("nombre")
        max_invitados = r.get("max_invitados")

        evento = Evento.objects.create(
            nombre=nombre,
            dueño=self.request.user.perfil,
            max_invitados=max_invitados,
        )

        if "text/html" in self.request.accepted_media_type:
            return HttpResponseRedirect(reverse_lazy('vehiculos:crear_evento'))
        else:
            return JsonResponse(EventoSerializer(evento).data, safe=False)


# Vista de la pantalla para Crear Invitación
class CreateInvitationView(GenericAPIView):
    template_name = 'vehiculos/crear_invitacion.html'
    renderer_classes = [JSONRenderer, TemplateHTMLRenderer]

    permission_classes = [IsAuthenticated, IsEventOwner]

    def get_context_data(self, **kwargs):
        context = {}

        eventos = Evento.objects.filter(dueño=self.request.user.perfil)
        context["eventos"] = EventoSerializer(eventos, many=True).data
        return context

    def get(self, request):
        """Método Get: pasa todo el contexto necesario para la vista."""
        context = self.get_context_data()
        return Response(context)

    def post(self, request):
        """Método Post: maneja la creación del invitación."""

        r = request.POST
        num_placas = r.get("num_placas")
        evento_id = r.get("evento_id")

        invitado = Invitado.objects.create(
            num_placas=num_placas,
            evento=Evento.objects.get(id=evento_id),
        )

        try:
            vehiculo = Vehiculo.objects.get(num_placas=num_placas)
            invitado.vehiculo = vehiculo
            invitado.save()
        except Vehiculo.DoesNotExist:
            pass

        if "text/html" in self.request.accepted_media_type:
            return HttpResponseRedirect(
                reverse_lazy('vehiculos:crear_invitacion')
            )
        else:
            return JsonResponse(InvitadoSerializer(invitado).data, safe=False)


# Vista de la pantalla para Invitation Status
class InvitationStatusView(GenericAPIView):
    template_name = 'vehiculos/status_invitacion.html'
    renderer_classes = [JSONRenderer, TemplateHTMLRenderer]
    permission_classes = [IsAuthenticated, IsStaff]

    def get_context_data(self, **kwargs):
        context = {}
        eventos = Evento.objects.all()
        context["eventos"] = eventos
        return context

    def get(self, request):
        """Método Get: pasa todo el contexto necesario para la vista."""
        context = self.get_context_data()
        return Response(context)

    def patch(self, request):
        """Método Patch: maneja el check in y check out."""
        r = request.POST
        invitado_id = r.get("invitado_id")
        accion = r.get("accion")
        invitado = Invitado.objects.get(id=invitado_id)
        if accion == "check_in":
            if not (invitado.hora_entrada) and not (invitado.hora_salida):
                invitado.hora_entrada = datetime.datetime.now()
        if accion == "check_out":
            if invitado.hora_entrada and not (invitado.hora_salida):
                invitado.hora_salida = datetime.datetime.now()
        invitado.save()

        return JsonResponse(InvitadoSerializer(invitado).data, safe=False)


# Vista de la pantalla para Obtener Invitaciones
class GetInfoView(GenericAPIView):
    renderer_classes = [JSONRenderer]
    permission_classes = [IsAuthenticated, IsStaff]

    def get_vehiculo_info(self, **kwargs):
        num_placas = self.request.GET.get("num_placas")

        vehiculo = Vehiculo.objects.get(num_placas=num_placas)
        invitaciones = Invitado.objects.filter(
            vehiculo=vehiculo
        ).annotate(status=Case(
            When(hora_entrada__isnull=False,
                 hora_salida__isnull=False, then=Value("finish")),
            When(hora_entrada__isnull=False, then=Value("check_out")),
            default=Value("check_in"),
            output_field=CharField(),
        ))
        return vehiculo, invitaciones

    def get_invitados(self, **kwargs):
        evento_id = self.request.GET.get("evento_id")
        search = self.request.GET.get("search")

        invitados = Invitado.objects.filter(
            evento=evento_id
        ).annotate(status=Case(
                When(hora_entrada__isnull=False,
                     hora_salida__isnull=False, then=Value("finish")),
                When(hora_entrada__isnull=False, then=Value("check_out")),
                default=Value("check_in"),
                output_field=CharField(),
            ),
        )
        if search:
            invitados = invitados.filter(num_placas__icontains=search)
        return invitados

    def get_eventos(self, **kwargs):
        search = self.request.GET.get("search")
        eventos = Evento.objects.all()
        if search:
            eventos = eventos.filter(nombre__icontains=search)
        return eventos

    def get(self, request):
        """Método Get: pasa todo el contexto necesario para la vista."""
        modelo = self.request.GET.get("modelo")
        if modelo == "vehiculo":
            vehiculo, invitaciones = self.get_vehiculo_info()
            vehiculo_serializer = VehiculoSerializer(vehiculo)
            invitaciones_serializer = InvitadoSerializer(
                invitaciones,
                many=True
            )
            return JsonResponse(
                {
                    "vehiculo": vehiculo_serializer.data,
                    "invitaciones": invitaciones_serializer.data
                },
                safe=False
            )
        elif modelo == "invitado":
            invitados = self.get_invitados()
            invitados_serializer = InvitadoSerializer(invitados, many=True)
            return JsonResponse(invitados_serializer.data, safe=False)
        elif modelo == "evento":
            eventos = self.get_eventos()
            eventos_serializer = EventoSerializer(eventos, many=True)
            return JsonResponse(eventos_serializer.data, safe=False)

templates/vehiculos/crear_evento.html
{% extends 'base.html' %}
{% load static %}

{% block head_content %}
<title>Crear Evento</title>
{% endblock %}

{% block container %}

    <form class="login-form" method="POST" action="{% url "vehiculos:crear_evento" %}">
        {% csrf_token %}

        <input type="text" name="nombre" id="nombre" placeholder="Nombre">
        <input type="text" name="max_invitados" id="max_invitados" placeholder="Max. invitados">

        <button class="log-in-button">
            Crear Evento
        </button>

    </form>
{% endblock%}

templates/vehiculos/crear_invitacion.html
{% extends 'base.html' %}
{% load static %}

{% block head_content %}
<title>Crear Invitación</title>
{% endblock %}

{% block container %}

    <form class="login-form" method="POST" action="{% url "vehiculos:crear_invitacion" %}">
        {% csrf_token %}

        <input type="text" name="num_placas" id="num_placas" placeholder="Num placas">
        <select name="evento_id" id="evento_id">
            {% for evento in eventos %}
            <option value="{{evento.id}}">{{evento.nombre}}</option>
            {% endfor %}
        </select>

        <button class="log-in-button">
            Crear Invitación
        </button>

    </form>
{% endblock%}

templates/vehiculos/registro.html
{% extends 'base.html' %}
{% load static %}

{% block head_content %}
<title>Registrar Vehículo</title>
{% endblock %}

{% block container %}

    <form class="login-form" method="POST" action="{% url "vehiculos:registro_vehiculo" %}">
        {% csrf_token %}

        <input type="text" name="marca" id="marca" placeholder="Marca">
        <input type="text" name="modelo" id="modelo" placeholder="Modelo">
        <input type="text" name="num_serie" id="num_serie" placeholder="Num. serie">
        <input type="text" name="num_placas" id="num_placas" placeholder="Placas">

        <button class="log-in-button">
            Registrar Vehículo
        </button>

    </form>
{% endblock%}

templates/vehiculos/status_invitacion.html
{% extends 'base.html' %}
{% load static %}

{% block head_content %}
<title>Status Invitación</title>

<!-- Incluye jQuery (asegúrate de que esté incluido antes de Select2) -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<!-- Incluye las hojas de estilo de Select2 -->
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />

<!-- Incluye la biblioteca Select2 -->
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
{% endblock %}

{% block container %}

    <div>
        {% csrf_token %}

        <select name="evento_id" id="evento_id">
            <option value="">-- Evento --</option>
            {% for evento in eventos %}
            <option value="{{evento.id}}">{{evento.nombre}}</option>
            {% endfor %}
        </select>

        <div class="invitado-id-div" hidden>
            <select name="invitado_id" id="invitado_id">
                <option value="">-- Invitado --</option>
            </select>
        </div>

        <div class="button-div">
        </div>

    </div>
    <script>

        $(document).ready(function() {
            $('#evento_id').select2({
                width: '100%',
                ajax: {
                    type: 'GET',
                    dataType: 'json',
                    url: "{% url 'vehiculos:get_info' %}",
                    delay: 250,
                    headers: {
                        "X-CSRFToken": Cookies.get("csrftoken")
                    },
                    data: function(params) {
                        return {
                            modelo: "evento",
                            search: params.term
                        };
                    },
                    processResults: function(data) {
                        var results = [];
                        for (var i = 0; i < data.length; i++) {
                            results.push({
                                id: data[i].evento_id,
                                text: data[i].nombre,
                            });
                        }
                        return {
                            results: results
                        };
                    },
                    cache: true
                },
            }).on('select2:select', function (e) {
                $(".invitado-id-div").show()
            })

            $('#invitado_id').select2({
                width: '100%',
                ajax: {
                    type: 'GET',
                    dataType: 'json',
                    url: "{% url 'vehiculos:get_info' %}",
                    delay: 250,
                    headers: {
                        "X-CSRFToken": Cookies.get("csrftoken")
                    },
                    data: function(params) {
                        return {
                            modelo: "invitado",
                            evento_id: $("#evento_id").val(),
                            search: params.term
                        };
                    },
                    processResults: function(data) {
                        var results = [];
                        for (var i = 0; i < data.length; i++) {
                            results.push({
                                id: data[i].invitado_id,
                                text: data[i].num_placas,
                                status: data[i].status
                            });
                        }
                        return {
                            results: results
                        };
                    },
                    cache: true
                },
            }).on('select2:select', function (e) {
                var data = e.params.data;
                var status = data.status;

                $(".button-div").empty()

                if (status == "check_in") {
                    $(".button-div").append($('<button>', {
                        text: "Check in",
                        onclick: "perform_check_in();",
                    }));
                }
                else if (status == "check_out") {
                    $(".button-div").append($('<button>', {
                        text: "Check out",
                        onclick: "perform_check_out();",
                    }));
                }
            });
        })


        function perform_check_in() {
            data = {}
            var invitado_id = $("#invitado_id").val()
            data.invitado_id = invitado_id;
            data.accion = "check_in";
            data._method = "PATCH";
            $.ajax({
                type: 'POST',
                data: data,
                success: function (response) {
                    window.location.reload()
                }
            })
        }

        function perform_check_out() {
            data = {}
            var invitado_id = $("#invitado_id").val()
            data.invitado_id = invitado_id;
            data.accion = "check_out";
            data._method = "PATCH";
            $.ajax({
                type: 'POST',
                data: data,
                success: function (response) {
                    window.location.reload()
                }
            })
        }
    </script>
{% endblock%}