PruebaCapital/urls.py
# Django
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include(("usuarios.urls", "usuarios"), namespace="usuarios")),
    path("", include(("vehiculos.urls", "vehiculos"), namespace="vehiculos")),
]

usuarios/urls.py
# Django
from django.urls import path

# View
from usuarios import views


urlpatterns = [
    path(
        route="login",
        view=views.LoginView.as_view(),
        name='login'
    ),
    path(
        route="logout",
        view=views.LogoutView.as_view(),
        name='logout'
    ),
    path(
        route="signup",
        view=views.SignupView.as_view(),
        name='signup'
    ),
]

templates/users/login.html
{% extends 'base.html' %}
{% load socialaccount %}
{% load static %}

{% block head_content %}
<title>Iniciar sesión</title>
{% endblock %}

{% block container %}

    {% if form.errors %}
        <p class="login-text"><i class="fas fa-exclamation-triangle"></i> Su nombre de usuario y contraseña no coinciden. Inténtalo de nuevo.</p>
    {% endif%}

    <form class="login-form" method="POST" action="{% url "usuarios:login" %}">
        {% csrf_token %}

        <input type="text" name="username" id="username" placeholder="Usuario/Email">
        <input type="password" name="password" id="password" placeholder="Contraseña">

        <div class="login-options-container">
            <p>¿No te has registrado aún? <a href="{% url 'usuarios:signup' %}">Regístrate!</a></p>
        </div>

        <button class="log-in-button">
            Iniciar sesión
        </button>

    </form>
{% endblock%}

templates/users/signup.html
{% extends 'base.html' %}
{% load static %}

{% block head_content %}
<title>Registrarse</title>
{% endblock %}

{% block container %}

    <form class="signup-form" action="{% url "usuarios:signup" %}" method="POST">
        {% csrf_token %}

        {% if form.errors.1 %}
            <p class="login-text"><i class="fas fa-exclamation-triangle"></i> {{form.errors.1}}</p>
        {% endif %}

        {{form}}

        {{help_text}}
        
        <p>¿Ya tienes una cuenta? <a href="{% url 'usuarios:login' %}">Iniciar sesión aquí</a></p>

        <button type="submit" class="signup-button">
            Registrar!
        </button>

    </form>

    <script>

        function without_space(e) {
            e.value = e.value.replace(/ /g, '').replace(/\//g, '');
        }
    </script>
{% endblock%}